name: Build Release Binary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Export Signing Config
      working-directory: app
      run: |
        echo $KEYSTORE_FILE | base64 --d > BluBot.jks
        echo $SIGNING_PROPERTIES | base64 --d > signing.properties
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Bundle with Gradle
      run: ./gradlew bundleRelease
